


POST http://localhost:3000/events/fetch-events

###

GET http://localhost:3000/events/

###

DELETE http://localhost:3000/events/


### Event_id

GET http://localhost:3000/event_ids

###
DELETE http://localhost:3000/event_ids